server {
    listen 0.0.0.0:8080;
    server_name localhost lilou;
    root ./srv/www;

    index index.html;
    error_page 400 ./srv/www/customErrorPages/400.html;
    error_page 403 ./srv/www/customErrorPages/403.html;
    error_page 404 ./srv/www/customErrorPages/404.html;
    error_page 405 ./srv/www/customErrorPages/405.html;
    error_page 413 ./srv/www/customErrorPages/413.html;
    error_page 500 ./srv/www/customErrorPages/500.html;
    error_page 501 ./srv/www/customErrorPages/501.html;
    error_page 504 ./srv/www/customErrorPages/504.html;

    max_body_size 1M;
    allow_methods GET;
    autoindex off;

    location / {
        root ./srv/www;
        allow_methods GET;
    }

    location /upload {
        root ./srv/www;
        autoindex on;
        upload_path ./srv/www/upload;
        allow_methods POST DELETE GET;
        max_body_size 2M;
    }

    location /session {
        allow_methods GET POST;
    }

    location /redirect_ext {
        return 301 http://google.com;
    }

    location /redirect_int {
        return 302 /index.html;
    }

    location /cgi {
        root ./srv/www;
        allow_methods GET POST;
        cgi_extension .py /usr/bin/python3;
        cgi_extension .sh /bin/sh;
    }
}

server {
    listen 0.0.0.0:8081;
    server_name cat.com;
    root ./eval_site_a;
    index index.html;
    error_page 404 ./eval_errors/404.html;
    max_body_size 10M;
    allow_methods GET POST;
}

server {
    listen 0.0.0.0:8083;
    server_name dog.com;
    root ./eval_site_b;
    index index.html;
    error_page 404 ./eval_errors/404.html;
    max_body_size 10M;
    allow_methods GET POST;
}
