server {
    listen 0.0.0.0:8080;
    server_name localhost lilou;
    root ./srv/www;

    index index.html;
    error_page 404 /custom_404.html;
    error_page 502 /custom_502.html;
    error_page 504 /custom_504.html;

    max_body_size       1M;
    allow_methods GET;
    autoindex off;

    location / {
        root ./srv/www;
        allow_methods GET;
    }

    location /uploads {
        root ./srv/www;                   
        upload_path ./uploads;         
        allow_methods POST DELETE;
        max_body_size       2M;
    }

    location /test_dir {
    root ./srv/www;
    autoindex on; # 👈 显式开启目录列表展示
    }

    location /test/index.html {
        allow_methods GET;
    }

    location /redirect_ext {
       return 301 http://google.com; 
    }

    location /redirect_int {
       return 302 /index.html; 
    }

    location /cgi-bin {
        root ./srv/www; 
        allow_methods GET POST;
        cgi_extension .py /usr/bin/python3;
    }

    location /cgi-php {
        root ./srv/www/cgi-scripts;
        allow_methods GET POST;
        cgi_extension .php /usr/bin/php-cgi;
    }

    location /login {
        root ./srv/www/login;
        index login_index.html;
        allow_methods GET POST;
        cgi_extension .py /usr/bin/python3;
    }

    location /auth {
        root ./srv/www/auth;      
        allow_methods GET;               
        cgi_extension .py /usr/bin/python3;
    }

    location /logout {
        root ./srv/www/logout;
        allow_methods POST;
        cgi_extension .py /usr/bin/python3;
    }

    location /files {
        root ./srv/www/files;
        autoindex on;
    }
}

server {
    listen 0.0.0.0:8081;
    server_name cat.com;
    index cat_index.html;
    root ./srv/www;
    error_page 404 /custom_404.html;

    max_body_size       10M;
    allow_methods GET POST;
}

server {
    listen 0.0.0.0:8083;
    server_name dog.com;
    index dog_index.html;
    root ./srv/www;
    error_page 404 /custom_404.html;
 
    max_body_size       10M;
    allow_methods GET POST;
}

