server {
	listen 127.0.0.1:8081;
	root srv/www;
		error_page 400 srv/www/customErrorPages/400.html;
		error_page 403 srv/www/customErrorPages/403.html;
		error_page 404 srv/www/customErrorPages/404.html;
		error_page 405 srv/www/customErrorPages/405.html;
		error_page 413 srv/www/customErrorPages/413.html;
		error_page 500 srv/www/customErrorPages/500.html;
		error_page 501 srv/www/customErrorPages/501.html;
		error_page 504 srv/www/customErrorPages/504.html;
	index index.html;
}
