server {
    listen 127.0.0.1:8080;
    server_name eval.local;
    root ./eval_site_a;
    index index.html;
    autoindex off;
    max_body_size 100;
    allow_methods GET POST DELETE;
    upload_path upload;

    error_page 404 $(pwd)/eval_errors/404.html;

    location /readonly/ {
        allow_methods GET;
    }

    location /upload/ {
        allow_methods GET POST DELETE;
        upload_path upload;
    }

    location /list/ {
        allow_methods GET;
        autoindex on;
    }

    location /no-list/ {
        allow_methods GET;
        autoindex off;
    }

    location /default/ {
        allow_methods GET;
        index home.html;
    }

    location /mapped/ {
    alias ./eval_mapped;
    allow_methods GET;
    }

    location /cgi/ {
    root ./eval_site_a;
    allow_methods GET POST;
    cgi_extension .py /usr/bin/python3;
    }

    location /old/ {
    return 301 /new/;
    }



}
