server {
	listen 127.0.0.1:8080;
	root srv/www;
	index index.html;
	error_page 404 srv/www/customErrorPages/404.html;
}

server {
	listen 127.0.0.1:9090;
	root srv/www;
	index indexBis.html;
	error_page 404 srv/www/customErrorPages/404bis.html;
}