server {
    listen 0.0.0.0:8080;
    server_name localhost;

    root ./tester_data/YoupiBanane;
    index youpi.bad_extension;
    max_body_size 120M;


    location / {
        root ./tester_data/YoupiBanane;
        index youpi.bad_extension;
        autoindex off;
        allow_methods GET;
        cgi_extension .bla ./tester_data/cgi_tester;
    }


    location /post_body {
        root ./tester_data/YoupiBanane;
        upload_path uploads;
        allow_methods POST;
        max_body_size 100;
    }


    location /directory {
        alias ./tester_data/YoupiBanane;
        index youpi.bad_extension;
        autoindex off;

        allow_methods GET POST;

        cgi_extension .bla ./tester_data/cgi_tester;

        # 42 tester:
        # URI 中的 .bla 不要求真实存在
        cgi_require_target off;
    }
}