server {
    listen       0.0.0.0:8080;
    server_name  localhost;

    root         ./tester_data/YoupiBanane;
    index        youpi.bad_extension;
    max_body_size 10M;

    # 1. / 路由
    location / {
        root          ./tester_data/YoupiBanane;
        index         youpi.bad_extension;
        autoindex     on;
        allow_methods GET POST;
        cgi_extension .bla ./tester_data/cgi_tester;
    }

    # 2. /post_body 路由
    location /post_body {
        root          ./tester_data/YoupiBanane;
        allow_methods POST;
        max_body_size 100;
    }

    # 3. /directory 路由
    location /directory{
        alias        ./tester_data/YoupiBanane;
        index         youpi.bad_extension;
        autoindex     on;
        allow_methods GET POST;
        cgi_extension .bla ./tester_data/cgi_tester;
    }
}