# duplicate_domain.conf
# 目的：两栋别墅都监听 80 端口，且共享了 "bad_boy.com" 域名
# 预期结果：解析到第二个 server 块结束时，必须精准熔断，绝不允许开机！

server {
    listen       80;
    server_name  normal.com bad_boy.com;
    root         /var/www;
}

server {
    listen       80;
    server_name  bad_boy.com; # 🚀 投毒点：在 80 端口上跟第一栋别墅打架抢资源！
    root         /var/www/other;
}